### ISSUE TITLE
Cannot exit elm-live process with keyboard shortcut

### ISSUE THREAD

**Issue by SidneyNemzer** [tomekwi/elm-live#108]
I'm unable to exit the elm-live process with `Ctrl` + `C` or `Ctrl` + `Z` on Windows when using:

* Bash on Ubuntu on Windows
* Git's built-in Bash

However, in Window's Powershell or true "Bash on Ubuntu", I CAN stop the process with `Ctrl` + `C`.

Tested on Windows 10

Any ideas what might be causing this?

**Comment by tomekwi** [comment]
Hey @SidneyNemzer, thanks for reporting! Interesting – I’ve never heard of this. Have you had this issue with other programs or servers as well?

**Comment by SidneyNemzer** [comment]
Sorry, it turns out this is a known issue with Bash on Ubuntu on Windows. Not an issue with elm-live.

Thanks for your reply though!
