### ISSUE TITLE
Syntax error in node v0.12.7

### ISSUE THREAD

**Issue by berndca** [tomekwi/elm-live#2]
elm-live/bin/elm-live.js:25
    reactor.on('error', (error) => {
                                ^^
    SyntaxError: Unexpected token =>
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)

**Comment by berndca** [comment]
I compiled elm-live.js to ES5. Works well, thanks!

**Comment by tomekwi** [comment]
Oops, sorry! I wanted to skip the build step – and in the end I’ve forgotten to document it.

I’ve put warnings where necessary now: @167a229 @d17d43e.

Thanks for the catch! Great to hear that it works transpiled!
