### ISSUE TITLE
elm-live not detecting file changes

### ISSUE THREAD

**Issue by hiaw** [tomekwi/elm-live#23]
elm-live was working for me and then it suddenly stop detecting file changes. I tried saving changes with Textmate, Emacs but it's just not detecting it.

The only significant thing happened in between is that I install MacTex and added `/Library/Tex/texbin` to the `PATH` environmental variable. But I can't imagine how that should affect it. 

Is there a way I can debug this?

**Comment by hiaw** [comment]
Never mind. I saved my file as `.Elm` instead of `.elm`

**Comment by tomekwi** [comment]
Thanks for letting me know! Glad that it worked out in the end :smiley:.
