### ISSUE TITLE
Display error message

### ISSUE THREAD

**Issue by martinos** [tomekwi/elm-live#36]
I am wondering if there is a way to display the error message in the browser? I personally really enjoyed when the errors were displayed.

**Comment by tomekwi** [comment]
Hello, thanks a lot for the feedback! However, unless *elm-make* supports such a feature, I don’t think this is doable within the scope of this project. This is just glue code between *elm-make* and the filesystem. Really sorry for this.

You should look at *elm-reactor* though if you want tighter integration with the browser. The reason this project was created in the first place is that *elm-reactor* was broken and hard to reconfigure at that time. Chances are it’s got better with 0.17 though. 😄 

Feel free to reopen if you think there’s something I should look at here.

**Comment by martinos** [comment]
Thanks for your response, I have been enjoying elm-live a lot. It gives a very nice workflow, I don't even have to run the compiler in my editor. I just need to look at the browser and see the change live. 

Not having a notification when the compiler failed was a bit annoying but I have just added triggers to iterm2 (on OS X) which now notifies me on errors. Now I am having a blast developing in Elm. Thanks for your work.

**Comment by tomekwi** [comment]
# 😄

**Comment by tomekwi** [comment]
Thanks for your kind words! I’m glad it helps!
