### ISSUE TITLE
Default host to `0.0.0.0`

### ISSUE THREAD

**Issue by tomekwi** [tomekwi/elm-live#94]
I find myself adding `--host=0.0.0.0` to almost every project, to be able to test my stuff on other computers in the network. I think this would make for a reasonable default, especially that it doesn’t break the current defaults (works with http://localhost and the local IP).

Is there anything I should keep in mind / watch out for?

**Comment by FMCorz** [comment]
I personally think the safer the better. Unless I'm mistaken the default for `elm-reactor` is also not allowing `0.0.0.0` by default.

**Comment by tomekwi** [comment]
Good point, let’s leave this open and see if we get other opinions.

**Comment by simonewebdesign** [comment]
Here's a similar discussion happened on [elm-reactor](https://github.com/elm-lang/elm-reactor/pull/99), looks like people tend to prefer localhost because it's safer.

**Comment by tomekwi** [comment]
Thanks a lot, super interesting link!

Now, that’s a very strong sign the community prefers the safer default. Thanks for the feedback again!
